---
- hosts: webserver
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: Loome publib_html kataloog user_ile
      file:
       path=/home/user/public_html
       owner=user
       group=user
       mode=0755
       state=directory
    - name: Apache2 serverile alg
      get_url:
        url: http://repo.mysql.com/mysql-apt-config_0.8.7-1_all.deb
        dest: "/root/allalaadimised"
        mode: 0440
    - name: install mysql
      apt: "deb=/root/allalaadimised/mysql-apt-config_0.8.7-1_all.deb"
    - name: install mysql
      apt: name=mysql-server update_cache=yes state=present
