---
- hosts: webservers
  tasks:
   - name: wpdb andmebaas
     mysql_db:
      name: wpdb
      state: present
   - name: 'wpuser' 'qwerty' konto
     mysql_user:
      name: wpuser
      password: qwerty
      priv: 'wpdb.*:ALL,GRANT'
      state: present
      check_implicit_admin: yes
   - name: mysql resa
     service: name=mysql state=restarted
   - name: wordpress download
     unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html/
      remote_src: yes
    - name: wordpress kausta omanik
     file:
      path: /var/www/html/wordpress/
      state: directory
      recurse: yes
      owner: www-data
   - name: conf backup
     command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wor$
   - name: db_password muutmine wordpressis
     lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="password_he$
   - name: db_user muutmine wordpressis
     lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="username_he$
   - name: db_name muutmine wordpressis
     lineinfile: dest=/var/www/html/wordpress/wp-config.php regexp="database_na$

